import type { Metadata } from 'next';
import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import localFont from 'next/font/local';
import Head from 'next/head';

const sora = localFont({
  src: [
    { path: './fonts/sora/Sora-Regular.woff', weight: '400', style: 'normal' },
    { path: './fonts/sora/Sora-SemiBold.woff', weight: '600', style: 'normal' },
    { path: './fonts/sora/Sora-Bold.woff', weight: '700', style: 'normal' }
  ],
  variable: '--font-sora'
});

const roboto = localFont({
  src: [
    {
      path: './fonts/roboto/Roboto-Regular.woff',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/roboto/Roboto-Medium.woff',
      weight: '500',
      style: 'normal'
    }
  ],
  variable: '--font-roboto'
});

const ppNeueMontrealBold = localFont({
  src: [
    {
      path: './fonts/pp-neue-montreal/PPNeueMontreal-Bold.woff',
      weight: '900',
      style: 'normal'
    }
  ],
  variable: '--font-pp-neue-montreal'
});

export const metadata: Metadata = {
  title: 'Odin Merchant Hub',
  description: 'Generated by Odin'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Head>
        {/* Title and Favicon */}
        <title>Odin Merchant Hub - Transforming Payment Processing</title>
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/img/Odin_black icon.png'
        />
        {/* SEO Meta Tags */}
        <meta
          name='description'
          content='Odin Merchant Hub offers innovative payment processing solutions tailored for Retail, services, e-commerce, and fintechs.'
        />
        <meta
          name='keywords'
          content='payment processing, Odin Merchant Hub, Point of sale, e-commerce payment solutions, fintech payments'
        />
        <meta name='robots' content='index, follow' />
        <meta name='author' content='Odin Merchant Hub' />
        {/* Open Graph and Twitter Meta Tags */}
        <meta
          property='og:title'
          content='Odin Merchant Hub - Transforming Payment Processing'
        />
        <meta
          property='og:description'
          content='Discover how Odin Merchant Hub’s payment solutions help optimize payment processing.'
        />
        <meta
          property='og:image'
          content='https://odinmerchanthub.com/images/og-image.jpg'
        />
        <meta property='og:url' content='https://odinmerchanthub.com' />
        <meta property='og:type' content='website' />
        <meta name='twitter:card' content='summary_large_image' />
        <meta
          name='twitter:title'
          content='Odin Merchant Hub - Payment Solutions'
        />
        <meta
          name='twitter:description'
          content="Optimize your payment operations with Odin Merchant Hub's tailored solutions."
        />
        <meta
          name='twitter:image'
          content='https://odinmerchanthub.com/images/twitter-image.jpg'
        />
      </Head>
      <body
        className={`${sora.variable} ${roboto.variable} ${ppNeueMontrealBold.variable} antialiased bg-main-background-color4`}>
        {children}
        {/* HubSpot Embed Code */}
        <script
          type='text/javascript'
          id='hs-script-loader'
          async
          defer
          src='//js.hs-scripts.com/47691275.js'></script>
      </body>
    </html>
  );
}
